# run this from the hvm/ directory

wasm-pack build --target web --out-dir wasm/web
wasm-pack build --target nodejs --out-dir wasm/nodejs
wasm-pack build --target bundler --out-dir wasm/bundler

# this is necessary because there seems to be no way
# to change the package name generated by wasm-pack

sed -i '' 's/"name": "hvm"/"name": "hvm-web"/' wasm/web/package.json
sed -i '' 's/"name": "hvm"/"name": "hvm-nodejs"/' wasm/nodejs/package.json
sed -i '' 's/"name": "hvm"/"name": "hvm-bundler"/' wasm/bundler/package.json
