name: rust_ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose

      - name: Install
        run: cargo install --path .

      - name: Run HVM files
        run: |
          bash -c 'find examples -name "*.hvm" | while read file; do
            echo "Running $file"
            hvm run "$file"
          done'
